'use strict';

/**
 * Render structured resume data into a clean navy-serif LaTeX template
 * (centered small-caps name, an icon contact line, ruled section headers, and
 * two-column entries with right-aligned dates). Mirrors the reference resume
 * design. Only the body is filled from extracted data; all user text is
 * LaTeX-escaped so arbitrary content compiles.
 *
 * Expected `data` shape (every field optional / forgiving):
 *   { name, location, email, phone,
 *     links:       [{ label, url }],
 *     education:   [{ institution, degree, date, score, coursework }],
 *     experience:  [{ company, title, location, date, bullets:[] }],
 *     projects:    [{ name, subtitle, tech, link, demo_link, bullets:[] }],
 *     skills:      [{ category, items }],
 *     profiles:    [{ label, detail, link }],   // e.g. Codeforces: Expert (1621)
 *     achievements:[{ label, detail }] | [str] }
 */

// Characters that must be escaped in LaTeX body text.
const SPECIALS = {
  '\\': String.raw`\textbackslash{}`,
  '&': String.raw`\&`,
  '%': String.raw`\%`,
  '$': String.raw`\$`,
  '#': String.raw`\#`,
  '_': String.raw`\_`,
  '{': String.raw`\{`,
  '}': String.raw`\}`,
  '~': String.raw`\textasciitilde{}`,
  '^': String.raw`\textasciicircum{}`,
};

const PREAMBLE = String.raw`%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Navy-serif resume template
% Generated by Job Apply Agent (resume import)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[10pt, a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\geometry{a4paper, top=1cm, bottom=1cm, left=1.4cm, right=1.4cm}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{fontawesome5}
\usepackage{hyperref}

\definecolor{navy}{RGB}{34, 38, 97}
\definecolor{bodygray}{RGB}{40, 40, 40}
\hypersetup{colorlinks=true, urlcolor=navy, linkcolor=navy, pdfborder={0 0 0}}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\color{bodygray}

% Ruled navy small-caps section headers
\titleformat{\section}
  {\color{navy}\scshape\large\bfseries}{}{0em}{}
  [\vspace{-0.5ex}{\color{navy}\titlerule[0.9pt]}\vspace{0.3ex}]
\titlespacing{\section}{0pt}{1.5ex}{0.7ex}

% Tight bullet list
\newlist{tight}{itemize}{1}
\setlist[tight]{label=\textbullet, leftmargin=1.5em, nosep, topsep=2pt, itemsep=1.5pt}

% left (bold) ... right (italic) on one line
\newcommand{\rowLR}[2]{\noindent{\bfseries #1}\hfill{#2}\par}
\newcommand{\rowsub}[2]{\noindent{\itshape #1}\hfill{\itshape #2}\par\vspace{0.2ex}}

% ATS: make copied/parsed text map to real Unicode (clean extraction).
\input{glyphtounicode}
\pdfgentounicode=1`;

function esc(value) {
  if (value == null) return '';
  let out = '';
  for (const ch of String(value)) {
    out += Object.prototype.hasOwnProperty.call(SPECIALS, ch) ? SPECIALS[ch] : ch;
  }
  return out;
}

function urlEsc(value) {
  if (!value) return '';
  return String(value).trim().split('%').join(String.raw`\%`).split('#').join(String.raw`\#`);
}

function asText(v) {
  return Array.isArray(v) ? v.map(String).join(', ') : String(v || '');
}

function bullets(items) {
  const list = (items || []).filter((b) => String(b).trim());
  if (!list.length) return '';
  const lines = [String.raw`\begin{tight}`];
  for (const b of list) lines.push(`  \\item ${esc(b)}`);
  lines.push(String.raw`\end{tight}`);
  return lines.join('\n');
}

// Pick a Font Awesome icon for a link based on its label.
function iconFor(label) {
  const l = String(label || '').toLowerCase();
  if (l.includes('linkedin')) return String.raw`\faLinkedin`;
  if (l.includes('github')) return String.raw`\faGithub`;
  if (l.includes('codeforces') || l.includes('leetcode') || l.includes('code')) return String.raw`\faCode`;
  if (l.includes('portfolio') || l.includes('website') || l.includes('site')) return String.raw`\faGlobe`;
  return String.raw`\faLink`;
}

function heading(d) {
  const parts = [];
  for (const link of d.links || []) {
    const url = urlEsc(link.url);
    const label = esc(link.label || 'Link');
    if (url) parts.push(`${iconFor(link.label)}~\\href{${url}}{${label}}`);
  }
  if (d.phone) parts.push(`\\faPhone~${esc(d.phone)}`);
  if (d.email) parts.push(`\\faEnvelope~\\href{mailto:${urlEsc(d.email)}}{${esc(d.email)}}`);
  const contact = parts.join(' \\quad ');
  return (
    '%----------HEADING----------\n' +
    '\\begin{center}\n' +
    `  {\\color{navy}\\Huge\\scshape ${esc(d.name)}}\\\\[0.7ex]\n` +
    `  {\\small ${contact}}\n` +
    '\\end{center}\n' +
    '\\vspace{0.4ex}'
  );
}

function education(items) {
  if (!items || !items.length) return '';
  const out = ['%----------EDUCATION----------', String.raw`\section*{Education}`];
  for (const e of items) {
    out.push(`\\rowLR{${esc(e.institution)}}{\\itshape ${esc(e.date)}}`);
    out.push(`\\rowsub{${esc(e.degree)}}{${esc(e.score)}}`);
    if (e.coursework) out.push(`{\\small \\textbf{Coursework:} ${esc(e.coursework)}\\par}`);
    out.push('\\vspace{0.4ex}');
  }
  return out.join('\n');
}

function experience(items) {
  if (!items || !items.length) return '';
  const out = ['%----------EXPERIENCE----------', String.raw`\section*{Work Experience}`];
  for (const e of items) {
    out.push(`\\rowLR{${esc(e.company)}}{\\itshape ${esc(e.date)}}`);
    if (e.title || e.location) out.push(`\\rowsub{${esc(e.title)}}{${esc(e.location)}}`);
    const body = bullets(e.bullets);
    if (body) out.push(body);
    out.push('\\vspace{0.5ex}');
  }
  return out.join('\n');
}

function projects(items) {
  if (!items || !items.length) return '';
  const out = ['%----------PROJECTS----------', String.raw`\section*{Projects}`];
  items.forEach((p, i) => {
    const name = esc(p.name);
    const sub = esc(p.subtitle);
    const title = name && sub ? `${name} : ${sub}` : name || sub;
    const links = [];
    if (urlEsc(p.link)) links.push(`\\href{${urlEsc(p.link)}}{Code}`);
    if (urlEsc(p.demo_link)) links.push(`\\href{${urlEsc(p.demo_link)}}{Live}`);
    const right = links.length ? `\\itshape ${links.join('~~')}` : '';
    out.push(`\\rowLR{\\#${i + 1}. ${title}}{${right}}`);
    const tech = asText(p.tech);
    if (tech) out.push(`{\\itshape \\small Tech Stack: ${esc(tech)}\\par}\\vspace{0.2ex}`);
    const body = bullets(p.bullets);
    if (body) out.push(body);
    out.push('\\vspace{0.5ex}');
  });
  return out.join('\n');
}

function skills(items) {
  if (!items || !items.length) return '';
  const out = ['%----------TECHNICAL SKILLS----------', String.raw`\section*{Technical Skills}`];
  for (const s of items) {
    const cat = esc(s.category);
    const it = esc(asText(s.items));
    if (cat && it) out.push(`\\noindent\\textbf{${cat}:} ${it}\\par`);
    else if (cat || it) out.push(`\\noindent ${cat || it}\\par`);
  }
  return out.join('\n');
}

function profiles(items) {
  if (!items || !items.length) return '';
  const cells = items
    .map((p) => {
      const label = urlEsc(p.link)
        ? `\\href{${urlEsc(p.link)}}{${esc(p.label)}}`
        : esc(p.label);
      const detail = esc(p.detail);
      return `\\textbf{${label}:} ${detail}`;
    })
    .filter(Boolean);
  if (!cells.length) return '';
  return [
    '%----------CODING PROFILES----------',
    String.raw`\section*{Coding Profiles}`,
    `\\noindent ${cells.join(' \\hfill ')}\\par`,
  ].join('\n');
}

function achievements(items) {
  if (!items || !items.length) return '';
  const list = [];
  for (const a of items) {
    if (a && typeof a === 'object' && !Array.isArray(a)) {
      const label = esc(a.label);
      const detail = esc(a.detail);
      if (label && detail) list.push(`\\textbf{${label}:} ${detail}`);
      else if (label || detail) list.push(label || detail);
    } else if (String(a).trim()) {
      list.push(esc(a));
    }
  }
  if (!list.length) return '';
  const out = ['%----------ACHIEVEMENTS----------', String.raw`\section*{Achievements}`, String.raw`\begin{tight}`];
  for (const item of list) out.push(`  \\item ${item}`);
  out.push(String.raw`\end{tight}`);
  return out.join('\n');
}

// Sanitise text destined for PDF metadata (no braces/backslashes).
function metaSan(value) {
  return String(value == null ? '' : value).replace(/[{}\\]/g, '').slice(0, 140);
}

// Optional keyword-rich summary — present on specialised variants, boosts ATS.
function summary(d) {
  const s = String(d.summary || '').trim();
  if (!s) return '';
  return ['%----------SUMMARY----------', String.raw`\section*{Summary}`, `\\noindent ${esc(s)}\\par`].join('\n');
}

function renderResumeTex(data) {
  const d = data || {};
  const title = metaSan(d.name) + (d.target_role ? ` — ${metaSan(d.target_role)}` : '');
  const meta = `\\hypersetup{pdftitle={${title}}, pdfauthor={${metaSan(d.name)}}}`;
  const body = [
    heading(d),
    summary(d),
    education(d.education),
    experience(d.experience),
    projects(d.projects),
    skills(d.skills),
    profiles(d.profiles),
    achievements(d.achievements),
  ]
    .filter((section) => section)
    .join('\n\n');
  return `${PREAMBLE}\n${meta}\n\\begin{document}\n\n${body}\n\n\\end{document}\n`;
}

module.exports = { renderResumeTex, esc };
