"""Render structured resume data into the Friggeri LaTeX template.

The preamble is fixed (it mirrors ``tanay_agrawal_resume.tex``); only the body
is filled from extracted data. All user-supplied text is LaTeX-escaped so
arbitrary resume content compiles cleanly.

Expected ``data`` shape (every field optional / forgiving)::

    {
      "name": str, "location": str, "email": str, "phone": str,
      "links": [{"label": str, "url": str}],
      "education":  [{"degree": str, "institution": str, "date": str, "coursework": str}],
      "skills":     [{"category": str, "items": str}],
      "projects":   [{"name": str, "subtitle": str, "role": str, "link": str, "bullets": [str]}],
      "experience": [{"title": str, "company": str, "date": str, "bullets": [str]}],
      "achievements": [{"label": str, "detail": str}]  # or a list of plain strings
    }
"""

from __future__ import annotations

# Characters that must be escaped in LaTeX body text.
_SPECIALS = {
    "\\": r"\textbackslash{}",
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}",
    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}

_PREAMBLE = r"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Friggeri Resume/CV Template
%
% Generated by Job Apply Agent (LaTeX import)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[10pt, a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\geometry{a4paper, top=0.8cm, bottom=0.8cm, left=1.5cm, right=1.5cm}
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    urlcolor=blue,
    linkcolor=blue,
}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{xcolor}

\definecolor{gray}{RGB}{45, 45, 45}
\definecolor{lightgray}{RGB}{120, 120, 120}

\pagestyle{empty}
\setlength{\parindent}{0pt}

% Section formatting
\titleformat{\section}
  {\color{gray}\scshape\Large\raggedright}
  {}{0em}
  {}[\color{lightgray}\titlerule]
\titlespacing{\section}{0pt}{1.5ex}{1ex}

\titleformat{\subsection}
  {\bfseries\normalsize}
  {}{0em}{}
\titlespacing{\subsection}{0pt}{1ex}{0.5ex}

% Entry list style
\newlist{entrylist}{itemize}{1}
\setlist[entrylist]{label=\textbullet, leftmargin=*, nosep, itemsep=0.15em}

\begin{document}"""


def esc(value) -> str:
    """LaTeX-escape arbitrary body text."""
    if value is None:
        return ""
    return "".join(_SPECIALS.get(ch, ch) for ch in str(value))


def _url(value) -> str:
    """Minimal escaping for a URL placed inside ``\\href{...}``."""
    if not value:
        return ""
    return str(value).strip().replace("%", r"\%").replace("#", r"\#")


def _bullets(bullets) -> str:
    items = [b for b in (bullets or []) if str(b).strip()]
    if not items:
        return ""
    lines = ["\\begin{entrylist}"]
    lines += [f"    \\item {esc(b)}" for b in items]
    lines.append("\\end{entrylist}")
    return "\n".join(lines)


def _heading(d: dict) -> str:
    parts = [esc(d.get("location")), esc(d.get("email")), esc(d.get("phone"))]
    for link in d.get("links") or []:
        url = _url(link.get("url"))
        label = esc(link.get("label") or "Link")
        if url:
            parts.append(f"\\href{{{url}}}{{{label}}}")
    contact = " \\textbullet{} \n    ".join(p for p in parts if p)
    return (
        "%----------HEADING----------\n"
        "\\begin{center}\n"
        f"    {{\\Huge \\scshape {esc(d.get('name'))}}}\n"
        "    \\vspace{1ex}\n\n"
        f"    {contact}\n"
        "\\end{center}"
    )


def _education(items) -> str:
    if not items:
        return ""
    out = ["%----------EDUCATION----------", "\\section*{Education}"]
    for e in items:
        head = esc(e.get("degree"))
        inst = esc(e.get("institution"))
        if inst:
            head = f"{head}, {inst}" if head else inst
        date = esc(e.get("date"))
        datepart = f" \\hfill \\textit{{{date}}}" if date else ""
        out.append(f"\\subsection*{{{head}{datepart}}}")
        cw = esc(e.get("coursework"))
        if cw:
            out.append("\\begin{entrylist}")
            out.append(f"    \\item \\textbf{{Coursework:}} {cw}")
            out.append("\\end{entrylist}")
    return "\n".join(out)


def _skills(items) -> str:
    if not items:
        return ""
    out = ["%----------TECHNICAL SKILLS----------", "\\section*{Technical Skills}", "\\begin{entrylist}"]
    for s in items:
        cat = esc(s.get("category"))
        it = esc(s.get("items"))
        if cat and it:
            out.append(f"    \\item \\textbf{{{cat}:}} {it}")
        elif cat or it:
            out.append(f"    \\item {cat or it}")
    out.append("\\end{entrylist}")
    return "\n".join(out)


def _projects(items) -> str:
    if not items:
        return ""
    out = ["%----------PROJECTS----------", "\\section*{Projects}"]
    for p in items:
        name = esc(p.get("name"))
        sub = esc(p.get("subtitle"))
        title = f"{name} — {sub}" if (name and sub) else (name or sub)
        extras = []
        role = esc(p.get("role"))
        if role:
            extras.append(f"\\textit{{[{role}]}}")
        link = _url(p.get("link"))
        if link:
            extras.append(f"\\href{{{link}}}{{\\small{{[GitHub]}}}}")
        tail = (" \\hfill " + " ".join(extras)) if extras else ""
        out.append(f"\\subsection*{{{title}{tail}}}")
        body = _bullets(p.get("bullets"))
        if body:
            out.append(body)
    return "\n".join(out)


def _experience(items) -> str:
    if not items:
        return ""
    out = ["%----------EXPERIENCE----------", "\\section*{Experience}"]
    for e in items:
        title = esc(e.get("title"))
        company = esc(e.get("company"))
        head = f"{title}, {company}" if (title and company) else (title or company)
        date = esc(e.get("date"))
        datepart = f" \\hfill \\textit{{{date}}}" if date else ""
        out.append(f"\\subsection*{{{head}{datepart}}}")
        body = _bullets(e.get("bullets"))
        if body:
            out.append(body)
    return "\n".join(out)


def _achievements(items) -> str:
    if not items:
        return ""
    out = ["%----------ACHIEVEMENTS----------", "\\section*{Achievements}", "\\begin{entrylist}"]
    for a in items:
        if isinstance(a, dict):
            label = esc(a.get("label"))
            detail = esc(a.get("detail"))
            if label and detail:
                out.append(f"    \\item \\textbf{{{label}:}} {detail}")
            elif label or detail:
                out.append(f"    \\item {label or detail}")
        elif str(a).strip():
            out.append(f"    \\item {esc(a)}")
    out.append("\\end{entrylist}")
    return "\n".join(out)


def render_resume_tex(data: dict) -> str:
    """Build a complete, compilable LaTeX document from structured resume data."""
    data = data or {}
    body = "\n\n".join(
        section
        for section in (
            _heading(data),
            _education(data.get("education")),
            _skills(data.get("skills")),
            _projects(data.get("projects")),
            _experience(data.get("experience")),
            _achievements(data.get("achievements")),
        )
        if section
    )
    return f"{_PREAMBLE}\n\n{body}\n\n\\end{{document}}\n"
